import 'package:flutter/material.dart';

/// Íconos que se pueden elegir para una categoría propia.
///
/// Se guarda la clave (no el código del ícono): así el catálogo puede crecer y la
/// app sigue reduciendo la fuente de íconos al compilar.
const Map<String, IconData> customCategoryIcons = {
  'restaurante': Icons.restaurant_outlined,
  'cafe': Icons.local_cafe_outlined,
  'pizza': Icons.local_pizza_outlined,
  'hamburguesa': Icons.lunch_dining_outlined,
  'pastel': Icons.cake_outlined,
  'bar': Icons.local_bar_outlined,
  'carrito': Icons.shopping_cart_outlined,
  'bolsa': Icons.shopping_bag_outlined,
  'tienda': Icons.storefront_outlined,
  'ropa': Icons.checkroom_outlined,
  'bus': Icons.directions_bus_outlined,
  'auto': Icons.directions_car_outlined,
  'gasolina': Icons.local_gas_station_outlined,
  'moto': Icons.two_wheeler_outlined,
  'avion': Icons.flight_outlined,
  'hotel': Icons.hotel_outlined,
  'casa': Icons.home_outlined,
  'llave': Icons.key_outlined,
  'luz': Icons.bolt_outlined,
  'agua': Icons.water_drop_outlined,
  'wifi': Icons.wifi,
  'celular': Icons.phone_android_outlined,
  'tele': Icons.tv_outlined,
  'cine': Icons.movie_outlined,
  'musica': Icons.music_note_outlined,
  'juegos': Icons.sports_esports_outlined,
  'futbol': Icons.sports_soccer_outlined,
  'gimnasio': Icons.fitness_center_outlined,
  'spa': Icons.spa_outlined,
  'salud': Icons.medical_services_outlined,
  'medicina': Icons.medication_outlined,
  'escuela': Icons.school_outlined,
  'libro': Icons.menu_book_outlined,
  'bebe': Icons.child_care_outlined,
  'mascota': Icons.pets_outlined,
  'regalo': Icons.redeem_outlined,
  'fiesta': Icons.celebration_outlined,
  'ahorro': Icons.savings_outlined,
  'banco': Icons.account_balance_outlined,
  'tarjeta': Icons.credit_card_outlined,
  'pagos': Icons.payments_outlined,
  'trabajo': Icons.work_outline,
  'herramientas': Icons.handyman_outlined,
  'arreglo': Icons.build_outlined,
  'computadora': Icons.computer_outlined,
  'camara': Icons.camera_alt_outlined,
  'arte': Icons.brush_outlined,
  'lavanderia': Icons.local_laundry_service_outlined,
  'donacion': Icons.volunteer_activism_outlined,
  'corazon': Icons.favorite_border,
  'estrella': Icons.star_border,
  'planta': Icons.eco_outlined,
  'parque': Icons.park_outlined,
  'playa': Icons.beach_access_outlined,
  'maleta': Icons.luggage_outlined,
  'recibo': Icons.receipt_long_outlined,
  'inversion': Icons.trending_up,
  'flores': Icons.local_florist_outlined,
};

/// Ícono de una clave guardada; si ya no existe, uno genérico.
IconData customIconFor(String key) => customCategoryIcons[key] ?? Icons.label_outline;
